name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]       # push 到 main 分支触发 latest 镜像
    tags: [ "v*" ]             # push Git tag（如 v1.0.0）时触发版本镜像
  workflow_dispatch:           # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取仓库代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. 设置 Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 构建并推送镜像
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386
          tags: |
            v1st233/iptv:latest
            v1st233/iptv:${{ env.short_sha }}
